# Generated by Django 4.2.17 on 2024-12-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
